"""
run_hpc_sensitivity.py – Single Slurm task for the sensitivity analysis.

Reads SLURM_ARRAY_TASK_ID (or --task-id), looks up the (carry_shift,
variance_scale) from param_configs.csv (generated by config_matrix.py),
simulates n_sims full holes, and writes:

    outputs/sim_output_dist{D}_disp{S}.csv          all shot records
    outputs/sim_output_dist{D}_disp{S}_meta.json     config + stats
    outputs/sim_output_dist{D}_disp{S}_tee.json      tee shot summary
    outputs/sim_output_dist{D}_disp{S}_landing_map.png
    outputs/sim_output_dist{D}_disp{S}_score_dist.png
    outputs/sim_output_dist{D}_disp{S}_tee_shot.png

Usage (called by submit_hpc_sensitivity.sh):
    python run_hpc_sensitivity.py \\
        --task-id $SLURM_ARRAY_TASK_ID \\
        --configs-csv param_configs.csv \\
        --n-sims 1000 \\
        --output-dir outputs/ \\
        --data-dir /path/to/data
"""

from __future__ import annotations

import sys as _sys
if _sys.version_info < (3, 9):
    _sys.exit(f"ERROR: Python 3.9+ required, got {_sys.version}")

import argparse
import json
import logging
import os
from pathlib import Path

_HERE = Path(__file__).parent
_sys.path.insert(0, str(_HERE))

from config_matrix import build_config_matrix, get_config
from sim_full_hole import generate_sensitivity_plots, get_tee_summary, output_filename, run_sensitivity


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Single-task sensitivity analysis worker.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--task-id",     type=int, default=None,
                   help="Override SLURM_ARRAY_TASK_ID.")
    p.add_argument("--configs-csv", type=Path,
                   default=_HERE / "param_configs.csv",
                   help="Path to param_configs.csv (generated by config_matrix.py).")
    p.add_argument("--n-sims",      type=int, default=1_000,
                   help="Full holes to simulate per configuration.")
    p.add_argument("--gp-iter",     type=int, default=100,
                   help="GPR training iterations for the putting model.")
    p.add_argument("--aim-offset",  type=float, default=0.0,
                   help="Fixed lateral aim offset in yards (0 = aim at pin).")
    p.add_argument("--data-dir",    type=Path, default=None)
    p.add_argument("--output-dir",  type=Path, default=Path("outputs"))
    p.add_argument("--log-level",   default="INFO")
    return p.parse_args()


def main() -> None:
    args = _parse_args()

    # ── Resolve task ID ────────────────────────────────────────────────────
    task_id = args.task_id
    if task_id is None:
        raw = os.environ.get("SLURM_ARRAY_TASK_ID")
        if raw is None:
            _sys.exit("ERROR: --task-id not set and $SLURM_ARRAY_TASK_ID not found.")
        task_id = int(raw)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    log_dir = args.output_dir / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)

    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        handlers=[
            logging.StreamHandler(_sys.stdout),
            logging.FileHandler(log_dir / f"task{task_id:04d}.log"),
        ],
    )
    logger = logging.getLogger(__name__)
    logger.info(
        "Sensitivity worker | SLURM_JOB_ID=%s  task_id=%d",
        os.environ.get("SLURM_JOB_ID", "N/A"), task_id,
    )

    # ── Look up config ─────────────────────────────────────────────────────
    if args.configs_csv.exists():
        import pandas as pd
        df_configs = pd.read_csv(args.configs_csv)
    else:
        logger.warning("configs-csv not found at %s; regenerating.", args.configs_csv)
        df_configs = build_config_matrix()

    cfg = get_config(task_id, df_configs)
    carry_shift    = float(cfg["carry_shift"])
    variance_scale = float(cfg["variance_scale"])
    trend          = int(cfg["trend"])

    logger.info(
        "Config: task_id=%d  trend=%d  carry_shift=%.4f  variance_scale=%.4f",
        task_id, trend, carry_shift, variance_scale,
    )

    # ── Run simulation ─────────────────────────────────────────────────────
    data_dir = (
        Path(args.data_dir) if args.data_dir is not None
        else Path(__file__).parent.parent / "data"
    )

    df, hole = run_sensitivity(
        carry_shift=carry_shift,
        variance_scale=variance_scale,
        n_sims=args.n_sims,
        seed=task_id,
        data_dir=data_dir,
        gp_training_iter=args.gp_iter,
        aim_offset=args.aim_offset,
    )

    # ── Save CSV ───────────────────────────────────────────────────────────
    fname_base = output_filename(carry_shift, variance_scale)
    csv_path   = args.output_dir / f"{fname_base}.csv"
    df.to_csv(csv_path, index=False)
    logger.info("CSV saved → %s  (%d rows)", csv_path, len(df))

    # ── Tee shot summary ───────────────────────────────────────────────────
    tee_summary = get_tee_summary(df)
    tee_path = args.output_dir / f"{fname_base}_tee.json"
    with open(tee_path, "w") as f:
        json.dump(tee_summary, f, indent=2)
    logger.info(
        "Tee summary: top_club=%s  mean_landing=(%.1f, %.1f)",
        tee_summary.get("top_club", "N/A"),
        tee_summary.get("landing_mean_x", 0.0),
        tee_summary.get("landing_mean_y", 0.0),
    )

    # ── Metadata sidecar ───────────────────────────────────────────────────
    strokes_per_hole = df.groupby("sim_id")["shot_num"].max()
    meta = {
        "task_id":            task_id,
        "trend":              trend,
        "carry_shift":        carry_shift,
        "variance_scale":     variance_scale,
        "n_sims":             args.n_sims,
        "n_shots_total":      len(df),
        "mean_strokes":       float(strokes_per_hole.mean()),
        "std_strokes":        float(strokes_per_hole.std()),
        "output_file":        f"{fname_base}.csv",
        "tee_top_club":       tee_summary.get("top_club", "N/A"),
        "tee_mean_x":         tee_summary.get("landing_mean_x", 0.0),
        "tee_mean_y":         tee_summary.get("landing_mean_y", 0.0),
    }
    meta_path = args.output_dir / f"{fname_base}_meta.json"
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)

    # ── Generate images ────────────────────────────────────────────────────
    logger.info("Generating plots ...")
    generate_sensitivity_plots(
        df=df,
        hole=hole,
        carry_shift=carry_shift,
        variance_scale=variance_scale,
        output_dir=args.output_dir,
        fname_base=fname_base,
    )

    logger.info(
        "Task %d complete | %.2f mean strokes | tee club: %s | outputs in %s",
        task_id, meta["mean_strokes"], meta["tee_top_club"], args.output_dir,
    )
    print(json.dumps(meta))


if __name__ == "__main__":
    main()
